apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.app.name }}-webhook
webhooks:
- name: {{ .Values.webhook.name }}
  clientConfig:
    service:
      name: {{ .Values.app.name }}
      namespace: {{ .Values.app.namespace }}
      path: /mutate
    caBundle: {{ .Values.webhook.caBundle }}
  failurePolicy: {{ .Values.webhook.failurePolicy }}
  timeoutSeconds: {{ .Values.webhook.timeoutSeconds }}
  admissionReviewVersions: ["v1"]
  sideEffects: None
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
